// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDLGbF1agwKtEYPEBHILhyYpz0fKI9Cg',
    appId: '1:345657299558:web:ecf3d8cdbfd40ed81f13a7',
    messagingSenderId: '345657299558',
    projectId: 'cmsc23-smvillavicencio',
    authDomain: 'cmsc23-smvillavicencio.firebaseapp.com',
    storageBucket: 'cmsc23-smvillavicencio.appspot.com',
    measurementId: 'G-VTFFSBJZFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7XovfSAYItvNjkPmehyhgMyppE9aLTI',
    appId: '1:345657299558:android:7ec70198c2fff44b1f13a7',
    messagingSenderId: '345657299558',
    projectId: 'cmsc23-smvillavicencio',
    storageBucket: 'cmsc23-smvillavicencio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrZzJnK7QAEtQdOzNkhGIedEpotLCa9g',
    appId: '1:345657299558:ios:f5de063269cd173a1f13a7',
    messagingSenderId: '345657299558',
    projectId: 'cmsc23-smvillavicencio',
    storageBucket: 'cmsc23-smvillavicencio.appspot.com',
    iosClientId: '345657299558-3vv9akbd3lm86jvkj1579sfno2jbbjhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrZzJnK7QAEtQdOzNkhGIedEpotLCa9g',
    appId: '1:345657299558:ios:f5de063269cd173a1f13a7',
    messagingSenderId: '345657299558',
    projectId: 'cmsc23-smvillavicencio',
    storageBucket: 'cmsc23-smvillavicencio.appspot.com',
    iosClientId: '345657299558-3vv9akbd3lm86jvkj1579sfno2jbbjhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
